### ISSUE TITLE
React Native Oauth broken for Expo SDK 43+

### ISSUE THREAD

**Issue by pagreczner** [magiclabs/magic-js#257] opened 2021-12-27 16:24 UTC
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

The react native oauth extension does not support Expo SDK versions 43+. Described here in feature request as this feels part bug / part feature: https://github.com/magiclabs/magic-js/issues/256

### 🧩 Steps to Reproduce

Create new expo managed workflow with SDK versions 43+.
Follow steps to add Magic Link to the project. Run `expo start` and see error.

### 🤔 Expected behavior

No errors. The library continues to work as it had for Expo Version 42 and below.

### 😮 Actual behavior

Error that `@unimodules/core` is not accessible.

### 💻 Code Sample

Use vanilla integration steps from magic link website.

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | latest
| Browser          | expo / react native
| `yarn`           | latest
| Operating System | iOS

**Comment by smithki** [comment] 2021-12-28 18:15
Duplicate of #256

**Closed by smithki** 2021-12-28 18:15 UTC
Labels: 🐛 Bug Report, 🔍 Needs Triage
