### ISSUE TITLE
Error from `loginWithMagicLink` caused by disabled cookies cannot be caught

### ISSUE THREAD

**Issue by ValentaTomas** [magiclabs/magic-js#166] opened 2021-03-03 18:10 UTC
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

Magic SDK `loginWithMagicLink` does not throw a catchable error when the browser has disabled cookies.

### 🧩 Steps to Reproduce

1. Disable all cookies in Firefox Preferences > Privacy & Security > Enhanced Tracking Protection > Custom.
2. Load a webpage with CDN Magic SDK and execute the code in the "Code Sample".

### 🤔 Expected behavior

`loginWithMagicLink` should throw an error that we can catch in the `try/catch` block.

### 😮 Actual behavior

The error cannot be caught in the `try/catch` block.

![Screen Shot 2021-03-03 at 19 00 37](https://user-images.githubusercontent.com/49156497/109851269-c7bb4200-7c53-11eb-90dd-eef1d44c5618.png)

### 💻 Code Sample

```
    try {
      const result = await magic.auth.loginWithMagicLink({
        email: '<email>',
        showUI: false,
        redirectURI: ' <redirectURI>',
      })

    } catch (error) {
      console.log(error);
    }
    
```

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | CDN
| Browser          | Firefox 86.0 (64-bit)
| `yarn`           |
| Operating System | macOS

**Comment by smithki** [comment] 2021-03-03 18:51
This error appears to be raised in our iframe, but should not actually affect the flow other than to cause our storage service to use a memory-based fallback.

I gave this a try in our [hello world demo](https://go.magic.link/hello-world), but was not able to reproduce the behavior described here. These are the Firefox ETP settings I used:

<img width="777" alt="Screen Shot 2021-03-03 at 1 49 03 PM" src="https://user-images.githubusercontent.com/22753882/109856496-8ad95600-7c27-11eb-817d-f38ead905f01.png">

Is there any more context you can share to help isolate the issue more?

**Comment by ValentaTomas** [comment] 2021-03-03 19:29
Try it with "All cookies" option:
![Screen Shot 2021-03-03 at 20 28 52](https://user-images.githubusercontent.com/49156497/109861032-276b1a80-7c5f-11eb-8e7a-2f84bec9b8f6.png)

**Comment by smithki** [comment] 2021-03-03 19:38
> Try it with "All cookies" option:
> ![Screen Shot 2021-03-03 at 20 28 52](https://user-images.githubusercontent.com/49156497/109861032-276b1a80-7c5f-11eb-8e7a-2f84bec9b8f6.png)

I was able to reproduce with this setting. Will update this thread once the issue is resolved!

**Comment by smithki** [comment] 2021-03-17 21:32
This issue has been resolved in our iframe app, which means it can be caught now! We'll also consider updating `magic-sdk` soon to silently fail in this case.

**Closed by smithki** 2021-03-17 21:32 UTC
Labels: 🐛 Bug Report, 🔥 Priority 2

**Comment by ValentaTomas** [comment] 2021-03-22 11:22
I checked it out and it is working, thanks!
