### ISSUE TITLE
Magic does not work with web3.js 1.3.0

### ISSUE THREAD

**Issue by andreashouben** [magiclabs/magic-js#138] opened 2020-10-03 12:04 UTC
### ✅ Prerequisites

- ✅ Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- ✅ Are you running the latest SDK version?
- ✅ Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

When trying to retrieve Ethereum wallet accounts with web3js version 1.3.0 you'll get an error in the base-module saying "transport" is undefined.

**Note!** If you switch the web3 version to the former 1.2.11 it works!

### 🧩 Steps to Reproduce

Just use the codesandbox I provided:
https://codesandbox.io/s/xenodochial-allen-klvfn?file=/src/App.js
Enter a valid api key and your email address and submit the form.

### 🤔 Expected behavior

No Error and the account keys get printed in the console.

### 😮 Actual behavior

``` 
base-module.js:58 Uncaught (in promise) TypeError: Cannot read property 'post' of undefined
    at BaseModule.request (base-module.js:58)
    at eval (eval at z (eval.js:42), <anonymous>:693:14)
    at RequestManager.send (index.js:166)
    at sendRequest (index.js:859)
    at Eth.send [as getAccounts] (index.js:889)
    at _callee$ (App.js? [sm]:16)
    at tryCatch (eval at z (eval.js:42), <anonymous>:62:40)
    at Generator.invoke [as _invoke] (eval at z (eval.js:42), <anonymous>:288:22)
    at Generator.prototype.<computed> [as next] (eval at z (eval.js:42), <anonymous>:114:21)
    at asyncGeneratorStep (eval at z (eval.js:42), <anonymous>:3:24)
    at _next (eval at z (eval.js:42), <anonymous>:25:9)
```

### 💻 Code Sample

See code sandbox above

### 🌎 Environment

See versions in codesandbox.

**Comment by smithki** [comment] 2020-10-05 20:59
I believe this is the cause: https://github.com/ethereum/web3.js/commit/e7adda5727b1e5a003872fe0657bd47af2b64950#diff-11cbf793feb1c35899194d3a17c4ece4R166

I will have to dig deeper to find out why and whether it can be solved from our side. I have raised this issue with Web3 as well: https://github.com/ethereum/web3.js/issues/3737

Considering the breaking change was introduced from the Web3-side, I'd prefer if the solution was implemented there as well. If this is affecting our provider implementation, there's good reason to believe other providers may be affected as well.

**Comment by Ethella** [comment] 2020-10-09 23:21
@andreashouben You may revert the web3 back to web3@1.2.11 version to get around the issue

**Comment by andreashouben** [comment] 2020-10-12 19:17
Yes thanks.  That's what I did. I also noted that in my bug report :-)

**Comment by Ethella** [comment] 2020-10-19 20:38
Closing this, feel free to re-open this when an issue has occurred

**Closed by Ethella** 2020-10-19 20:38 UTC
Labels: 🐛 Bug Report, 🔍 Needs Triage
