### ISSUE TITLE
MetaMask not disconnecting cleanly

### ISSUE THREAD

**Issue by nick** [magiclabs/magic-js#526] opened 2023-05-25 15:11 UTC
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

I'm looking at <https://codesandbox.io/s/github/magiclabs/magic-demo-react-web3> and having trouble disconnecting from MetaMask then connecting again with Email.

### 🧩 Steps to Reproduce

1. Connect via MetaMask
2. Disconnect
3. Try to connect again... it auto connects to MetaMask without showing the option to connect with Email etc.

If I refresh the page after step 2, things work as expected

### 🤔 Expected behavior

After disconnecting, clicking 'Connect' again show show all options for connecting, including email

### 😮 Actual behavior

[What actually happened? Please include any error stack traces you encounter.]

### 💻 Code Sample

[If possible, please provide a code repository, gist, code snippet or sample files to reproduce the issue.]

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |
| Browser          |
| `yarn`           |
| Operating System |

**Comment by am-hernandez** [comment] 2023-07-07 17:10
Hi @nick,

I am not able to reproduce this issue with our demo app. [Check out this Loom recording of the flow](https://www.loom.com/share/c2cbc8de72c94dda9b010e649975ac72?sid=7b27dd1a-d4d3-4c6c-b5be-be594b3c16ac) and see how I connect with MetaMask, disconnect, and then connect with Email. All login options are present in the modal when I am reconnecting. No refreshing of the page was needed.

Would you happen to have a demo with this issue reproduced that I can check out?

If you are no longer experiencing this issue please let us know.

**Comment by am-hernandez** [comment] 2023-07-11 14:22
Closing this issue as it is not reproducible. Please feel free to comment with a reproducible code sample if the issue persists!

**Closed by am-hernandez** 2023-07-11 14:22 UTC
Labels: 🐛 Bug Report, 🔍 Needs Triage
