### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by RickGove** [magiclabs/magic-js#301] opened 2022-04-04 08:07 UTC
### ✅ Prerequisites

- [ Yes ] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [ Yes ] Are you running the latest SDK version?
- [ Yes ] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

./node_modules/magic-sdk/dist/es/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### 🧩 Steps to Reproduce

yarn add magic-sdk

### 🤔 Expected behavior

Not have console warnings

### 😮 Actual behavior

I have console warnings

[If possible, please provide a code repository, gist, code snippet or sample files to reproduce the issue.]

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | ^8.0.1
| Browser   -       | Chrome 97.0.4692.99 (Official Build) (64-bit)
| `yarn`           | 1.22.17
| Operating System | Linux

**Comment by smithki** [comment] 2022-04-04 16:59
Closing as duplicate of https://github.com/magiclabs/magic-js/issues/295

Suggested workarounds are described in that issue 👆

**Closed by smithki** 2022-04-04 16:59 UTC
Labels: 🐛 Bug Report, 🔍 Needs Triage
